### PR TITLE
Updated exceptions clauses to the new format supported by Python3

### PR DESCRIPTION
**Pull request by rdarrelbonner**
Updated exception clauses to use "as" instead of ",".

### CODE REVIEW

**Comment by mikz** [comment]
Travis build passed. Looks good!

**Comment by vdel26** [comment]
The tests actually failed due to the lack of keys https://travis-ci.org/3scale/3scale_ws_api_for_python/jobs/68057013 but somehow Travis marked is as good. Since secret env variables don't work in PRs from forks I will add this commit to a branch of our own.

**Comment by vdel26** [comment]
@rdarrelbonner I included your commit in this other PR (#18) for the reason said [above](https://github.com/3scale/3scale_ws_api_for_python/pull/17#issuecomment-115632670). Feel free to comment there.

**Comment by rdarrelbonner** [comment]
thanks @vdel26!

**Pull request closed without merging**
